# -*- coding: utf-8 -*-
"""Q1_Mahogany_FA1_Evacuado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDuHzNwQ9hPquw4_Wo2YjFQQLmwN4lPb
"""

import math

# ask the user to enter the first coordinates
x1 = float(input("Enter x1: "))
y1 = float(input("Enter y1: "))

#ask the user to enter the second coordinates
x2 = float(input("Enter x2: "))
y2 = float(input("Enter y2: "))

# Compute the distance
d = math.sqrt(pow(x2 - x1, 2) + pow(y2 - y1, 2))

#Display the result
print("The distance between the two points is:", d)